todoproject/todo/urls.py
from . import views
from django.urls import path
app_name = 'todo'
urlpatterns = [
    # path('',views.index,name='index'),
    # path('delete/<int:id>/',views.delete,name='delete'),
    # path('update/<int:id>/',views.update,name='update'),
    path('cview',views.TaskList.as_view(),name='cview'),
    path('cdetail/<int:pk>/',views.TaskDetail.as_view(),name='cdetail'),
    path('cupdate/<int:pk>/', views.TaskUpdate.as_view(), name='cupdate'),
    path('cdelete/<int:pk>/', views.TaskDelete.as_view(), name='cdelete'),

]

todoproject/todoproject/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from todoproject import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('todo.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root = settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

todoproject/todo/models.py
from django.db import models

# Create your models here.
class Task(models.Model):
    name = models.CharField(max_length=250)
    priority = models.IntegerField()
    date = models.DateField()

    def __str__(self):
        return self.name

todoproject/todo/forms.py
from django import forms

from todo.models import Task


class TaskForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = ['name','priority','date']

todoproject/todo/views.py
from django.shortcuts import render, redirect
from django.urls import reverse_lazy

from .forms import TaskForm
from .models import Task
from django.views.generic import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import UpdateView, DeleteView
# Create your views here.
class TaskList(ListView):
    model = Task
    template_name = 'index.html'
    context_object_name = 'task1'

class TaskDetail(DetailView):
    model = Task
    template_name = 'details.html'
    context_object_name = 'task'

class TaskUpdate(UpdateView):
    model = Task
    template_name = 'update.html'
    context_object_name = 'task'
    fields = ('name','priority','date')
    def get_success_url(self):
        return reverse_lazy('todo:cdetail',kwargs={'pk':self.object.id})

class TaskDelete(DeleteView):
    model = Task
    template_name = 'delete.html'
    success_url = reverse_lazy('todo:cview')




#
# def index(request):
#     task1 = Task.objects.all()
#     if request.method == 'POST':
#         name = request.POST.get('task')
#         priority = request.POST.get('priority')
#         date = request.POST.get('date')
#         task = Task(name=name,priority=priority,date=date)
#         task.save()
#         return redirect('/')
#
#     return render(request,'index.html',{'task1':task1})

# def details(request):
#     task = Task.objects.all()
#     return render(request,'details.html',{'task':task})

# def delete(request,id):
#     task = Task.objects.get(id=id)
#     if request.method == 'POST':
#         task.delete()
#         return redirect('/')
#     return render(request,'delete.html')

# def update(request,id):
#     task = Task.objects.get(id=id)
#     form = TaskForm(request.POST or None,instance=task)
#     if form.is_valid():
#         form.save()
#         return redirect('/')
#
#     return render(request,'update.html',{'form':form,'task':task})

todoproject/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>ToDo</title>
    <!-- CSS only -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
<link rel="stylesheet" href="{% static 'styles.css' %}">
</head>
<body>
{% block body %}
{% endblock %}
</body>
</html>

todoproject/templates/delete.html
{% extends 'base.html' %}
{% block body %}
<form method="post">
    {% csrf_token %}
<h4>Are you sure?</h4>
<button class="btn btn-danger" type="submit">OK</button>
</form>
{% endblock %}

todoproject/templates/details.html
{% extends 'base.html' %}
{% block body %}

 <h3>Tasks to be completed</h3>

            <div class=" shadow card">
                <div class="card-body">
                    <h5 class="card-title"> {{task.name}}</h5>
                    <p><b>{{task.priority}}</b></p>
                    <p><b>{{task.date}}</b></p>
                    <a class="btn btn-danger" href="{% url 'todo:cdelete' task.id %}">Done</a>
                    <a class="btn btn-warning" href="{% url 'todo:cupdate' task.id %}">Update</a>
                </div>
            </div><br>
{% endblock %}

todoproject/templates/index.html
{% extends 'base.html' %}
{% block body %}
<div class="container-fluid">
    <div class="row">
        <div class="col-md-12">
            <div class="banner">
                <div class="banner-text">
                <h1>ToDo</h1>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="container">
    <div class="row">
        <div class="col-md-6">
<form method="post" class="p-3 shadow">
    {% csrf_token %}
    <div class="form-group" >
        <input type="text" class="form-control" name="task" placeholder="task"><br>
    </div>
    <div class="form-group">
        <input type="text" class="form-control" name="priority" placeholder="priority"><br>
    </div>
    <div class="form-group" >
        <input type="date" class="form-control" name="date"><br>
    </div>
<!--    <div class="form-group">-->
        <input class="btn btn-success" type="submit">
<!--    </div>-->

</form>
    </div>
        <div class="col-md-6">
            <h3>Tasks to be completed</h3>
            {% for i in task1 %}
            <div class=" shadow card">
                <div class="card-body">
                    <h5 class="card-title"> {{i.name}}</h5>
                    <p><b>{{i.priority}}</b></p>
                    <p><b>{{i.date}}</b></p>
                    <a class="btn btn-danger" href="{% url 'todo:cdelete' i.id %}">Done</a>
                    <a class="btn btn-warning" href="{% url 'todo:cupdate' i.id %}">Update</a>
                </div>
            </div><br>
            {% endfor %}
        </div>
    </div>

</div>


{% endblock %}

todoproject/templates/update.html
{% extends 'base.html' %}
{% block body %}
<div class="card">
    <div class="card-header">
        <div class="card-title">
            Task update
            <div class="card-body">
                <form method="post">
                {% csrf_token %}
                {{form.as_p}}
                <button type="submit">Update</button>
                </form>

            </div>
        </div>
    </div>
</div>



{% endblock %}